export interface Article {
  id: string;
  title: string;
  slug: string;
  excerpt: string;
  content: string;
  category: string;
  categoryColor: string;
  author: string;
  authorRole: string;
  date: string;
  readTime: string;
  imageUrl: string;
  isFeatured: boolean;
  isBreaking: boolean;
}

export const MOCK_ARTICLES = [
  {
    id: "1",
    title: "MK Putuskan UU Cipta Kerja: Hak PHK Kembali ke Pengadilan, Bukan Menteri",
    slug: "mk-putuskan-uu-cipta-kerja-phk-pengadilan",
    excerpt: "Mahkamah Konstitusi mengabulkan guguan material testing UU Cipta Kerja, menyatakan pasal PHK harus kembali ke pengadilan. Keputusan ini dinilai melindungi hak pekerja.",
    content: "<p>JAKARTA - Mahkamah Konstitusi (MK) mengabulkan sebagian guguan material testing UU Nomor 11 Tahun 2020 tentang Cipta Kerja...</p>",
    category: "Putusan MK",
    categoryColor: "bg-purple-600",
    author: "Dr. Budi Santoso, SH., MH.",
    authorRole: "Ahkam Hukum Tata Negara",
    date: "2024-12-15",
    readTime: "8 min",
    imageUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800",
    isFeatured: true,
    isBreaking: true,
  },
  {
    id: "2",
    title: "Bedah Pasal 27 UU ITE: Ancaman Penjara Bagi Hoaks dan Ujaran Kebencian",
    slug: "bedah-pasal-27-uu-ite-hoaks-ujaran-kebencian",
    excerpt: "Pasal 27 UU ITE sering diperdebatkan soal kebebasan berekspresi. Bedah tuntas pasal ini agar warganet bijak bermedia sosial.",
    content: "<p>Pasal 27 UU ITE mengatur tentang larangan menyebarkan informasi yang memuat ujaran kebencian...</p>",
    category: "Bedah Pasal",
    categoryColor: "bg-cyan-600",
    author: "Sarah Wijaya, SH.",
    authorRole: "Pengacara Cyber Law",
    date: "2024-12-10",
    readTime: "12 min",
    imageUrl: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800",
    isFeatured: false,
    isBreaking: false,
  },
  {
    id: "3",
    title: "MK Cabut Pasal Penjara di UU Pencemaran Nama Baik: Kemajuan HAM atau Bahaya?",
    slug: "mk-cabut-pasal-penjara-uu-pencemaran-nama-baik",
    excerpt: "MK menyatakan pasal penjara di UU Pencemaran Nama Baik bertentangan dengan UUD 1945. Keputusan ini dinilai sebagai kemajuan HAM signifikan.",
    content: "<p>Mahkamah Konstitusi mencabut pasal penjara dalam UU Pencemaran Nama Baik...</p>",
    category: "Putusan MK",
    categoryColor: "bg-purple-600",
    author: "Ahmad Fauzi, SH., MH.",
    authorRole: "Pengacara HAM",
    date: "2024-12-08",
    readTime: "10 min",
    imageUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800",
    isFeatured: false,
    isBreaking: true,
  },
  {
    id: "4",
    title: "Panduan Lengkap UU PDP: Hak Subjek Data & Kewajiban Pengendali Data",
    slug: "panduan-lengkap-uu-pdp-hak-subjek-data",
    excerpt: "UU Perlindungan Data Pribadi (PDP) berlaku penuh 2024. Simak hak Anda sebagai subjek data dan kewajiban perusahaan sebagai pengendali data.",
    content: "<p>UU Nomor 27 Tahun 2022 tentang Perlindungan Data Pribadi (PDP) resmi berlaku penuh...</p>",
    category: "Edukasi Hukum",
    categoryColor: "bg-blue-600",
    author: "Lisa Permata, SH., M.H.",
    authorRole: "Ahli Hukum Data",
    date: "2024-12-05",
    readTime: "15 min",
    imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800",
    isFeatured: false,
    isBreaking: false,
  },
  {
    id: "5",
    title: "Putusan MK Nomor 91/PUU-XVIII/2020: Perpanjangan Hak Tanggungan Otomatis",
    slug: "putusan-mk-perpanjangan-hak-tanggungan-otomatis",
    excerpt: "MK memutuskan perpanjangan hak tanggungan tidak perlu pengadilan lagi. Keputusan ini memberikan kepastian hukum bagi kreditur.",
    content: "<p>Putusan MK Nomor 91/PUU-XVIII/2020 mengubah lanskap jaminan fidusia di Indonesia...</p>",
    category: "Putusan MK",
    categoryColor: "bg-purple-600",
    author: "Prof. Dr. Andi Wijaya, SH.",
    authorRole: "Ahli Hukum Jaminan",
    date: "2024-12-01",
    readTime: "7 min",
    imageUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800",
    isFeatured: false,
    isBreaking: false,
  },
  {
    id: "6",
    title: "UU Pekerja Migran: Perlindungan TKI di Luar Negeri Perlu Diperkuat",
    slug: "uu-pekerja-migran-perlindungan-tki",
    excerpt: "UU Pekerja Migran baru dinilai belum sepenuhnya melindungi TKI. Advokat migran menuntut revisi pasal perlindungan hukum.",
    content: "<p>UU Pekerja Migran baru masih menyisakan celah perlindungan bagi TKI...</p>",
    category: "Hak Asasi",
    categoryColor: "bg-red-600",
    author: "Rina Kusuma, SH.",
    authorRole: "Advokat Migran",
    date: "2024-11-28",
    readTime: "9 min",
    imageUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800",
    isFeatured: false,
    isBreaking: false,
  },
  {
    id: "7",
    title: "KUHP Baru: Penghapusan Pasal Makar & Perubahan Ancaman Pidana Mati",
    slug: "kuhp-baru-penghapusan-pasal-makar",
    excerpt: "KUHP baru mencabut pasal makar dan mengubah pidana mati jadi pidana terberat. Pakar HAM menilai ini langkah progresif.",
    content: "<p>KUHP baru (UU No. 1/2023) membawa perubahan signifikan...</p>",
    category: "KUHP & Pidana",
    categoryColor: "bg-orange-600",
    author: "Dr. Siti Rahayu, SH., MH.",
    authorRole: "Ahli Hukum Pidana",
    date: "2024-11-25",
    readTime: "11 min",
    imageUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800",
    isFeatured: false,
    isBreaking: false,
  },
  {
    id: "8",
    title: "Hukum Acara Perdata: Panduan Gugatan Sederhana untuk Masyarakat",
    slug: "hukum-acara-perdata-gugatan-sederhana",
    excerpt: "Prosedur gugatan sederhana di pengadilan negeri kini lebih cepat dan murah. Panduan lengkap untuk masyarakat awam.",
    content: "<p>Gugatan sederhana (klein verzoek) diatur dalam HAP...</p>",
    category: "Edukasi Hukum",
    categoryColor: "bg-blue-600",
    author: "Bambang Sutrisno, SH.",
    authorRole: "Pengacara Perdata",
    date: "2024-11-20",
    readTime: "6 min",
    imageUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800",
    isFeatured: false,
    isBreaking: false,
  },
  {
    id: "9",
    title: "Perlindungan Hukum Anak: UU No. 11 Tahun 2012 vs UU No. 35 Tahun 2014",
    slug: "perlindungan-hukum-anak-uu-11-2012-vs-35-2014",
    excerpt: "Perbandingan UU Perlindungan Anak sebelum dan sesudah amandemen. Apa yang berubah untuk perlindungan anak konflik hukum?",
    content: "<p>UU No. 35 Tahun 2014 mengamandemen UU No. 11 Tahun 2012...</p>",
    category: "Hak Asasi",
    categoryColor: "bg-red-600",
    author: "Dewi Sartika, SH., MH.",
    authorRole: "Advokat Anak",
    date: "2024-11-15",
    readTime: "8 min",
    imageUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800",
    isFeatured: false,
    isBreaking: false,
  },
  {
    id: "10",
    title: "E-Commerce & Hukum: Perlindungan Konsumen di Transaksi Digital",
    slug: "e-commerce-hukum-perlindungan-konsumen-digital",
    excerpt: "UU Perlindungan Konsumen & UU PDP mengatur transaksi e-commerce. Apa hak konsumen saat barang tidak sesuai pesanan?",
    content: "<p>Transaksi e-commerce diatur dalam UU Perlindungan Konsumen dan UU PDP...</p>",
    category: "Edukasi Hukum",
    categoryColor: "bg-blue-600",
    author: "Andi Pratama, SH.",
    authorRole: "Ahli Hukum Digital",
    date: "2024-11-10",
    readTime: "7 min",
    imageUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800",
    isFeatured: false,
    isBreaking: false,
  },
];

export const MOCK_CATEGORIES = [
  { id: "putusan-mk", name: "Putusan MK", color: "bg-purple-600", count: 3 },
  { id: "bedah-pasal", name: "Bedah Pasal", color: "bg-cyan-600", count: 2 },
  { id: "edukasi-hukum", name: "Edukasi Hukum", color: "bg-blue-600", count: 2 },
  { id: "putusan-mk", name: "Putusan MK", color: "bg-purple-600", count: 3 },
  { id: "kuhp-pidana", name: "KUHP & Pidana", color: "bg-orange-600", count: 1 },
  { id: "hak-asasi", name: "Hak Asasi", color: "bg-red-600", count: 2 },
  { id: "edukasi-hukum", name: "Edukasi Hukum", color: "bg-blue-600", count: 2 },
];